modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/refinedmods/rangedpumps"
license = "MIT"
[[mods]]
modId = "rangedpumps"
version = "${version}"
displayName = "Ranged Pumps"
displayURL = "https://refinedmods.com/ranged-pumps"
authors = "Refined Mods"
description = '''
Ranged Pumps is a simple mod that adds a pump that pumps liquids in a range
'''
